# SciKit Learn Preprocessing Overview

In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[20, 72],
       [35,  9],
       [92, 49],
       [29, 44],
       [96, 52],
       [28, 57],
       [65, 99],
       [74, 92],
       [10, 59],
       [ 4, 94]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [7]:
scaler_model.fit(data)

/Users/robertlowe/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [8]:
scaler_model.transform(data)

array([[ 0.17391304,  0.7       ],
       [ 0.33695652,  0.        ],
       [ 0.95652174,  0.44444444],
       [ 0.27173913,  0.38888889],
       [ 1.        ,  0.47777778],
       [ 0.26086957,  0.53333333],
       [ 0.66304348,  1.        ],
       [ 0.76086957,  0.92222222],
       [ 0.06521739,  0.55555556],
       [ 0.        ,  0.94444444]])

In [9]:
# In one step
result = scaler_model.fit_transform(data)

/Users/robertlowe/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [10]:
result

array([[ 0.17391304,  0.7       ],
       [ 0.33695652,  0.        ],
       [ 0.95652174,  0.44444444],
       [ 0.27173913,  0.38888889],
       [ 1.        ,  0.47777778],
       [ 0.26086957,  0.53333333],
       [ 0.66304348,  1.        ],
       [ 0.76086957,  0.92222222],
       [ 0.06521739,  0.55555556],
       [ 0.        ,  0.94444444]])

In [11]:
import pandas as pd

In [12]:
mydata = np.random.randint(0,101,(50,4))

In [13]:
mydata

array([[56, 26, 82, 84],
       [50, 24,  5,  7],
       [55, 99, 55, 97],
       [14, 64, 43, 35],
       [34, 91, 78, 14],
       [23, 79, 98, 20],
       [76, 35, 49, 29],
       [49, 73, 34, 24],
       [79, 62, 64, 28],
       [86, 41, 97, 62],
       [50, 10,  4, 36],
       [91, 35, 43, 15],
       [ 0, 91, 39, 83],
       [80, 73, 62, 62],
       [18, 89,  4, 85],
       [74, 56, 51,  4],
       [14, 39, 67, 24],
       [68, 99, 62, 79],
       [29, 79, 69, 38],
       [49, 85, 67, 52],
       [46, 15, 86, 11],
       [85, 13,  7, 78],
       [80, 56, 91, 25],
       [16, 98,  8, 48],
       [36, 26, 12,  7],
       [51,  4, 91, 76],
       [85, 76, 59, 62],
       [71, 84, 13, 58],
       [42, 17, 19, 17],
       [60, 43, 20, 41],
       [33, 31, 21, 74],
       [47,  9, 70,  6],
       [47, 75, 67, 36],
       [89,  3, 20, 87],
       [38, 54, 86, 55],
       [62, 14, 23, 21],
       [25,  3, 32, 88],
       [11, 71, 78, 94],
       [40, 34,  2, 35],
       [76,  1, 67, 34],


In [14]:
data = pd.DataFrame(data=mydata,columns=['f1','f2','f3','label'])

In [15]:
data.head()

f1  f2  f3  label
0  56  26  82     84
1  50  24   5      7
2  55  99  55     97
3  14  64  43     35
4  34  91  78     14

In [16]:
x = data[['f1','f2','f3']] # Alternatively x = data.drop('label',axis=1)
y = data['label']

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=101)

In [21]:
X_train.shape

(35, 3)

In [22]:
X_test.shape

(15, 3)

In [23]:
y_train.shape

(35,)

In [24]:
y_test.shape

(15,)

## Great Job!